# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: 'Add conda to PATH'
- script: conda create --yes --quiet --name coderec
  displayName: 'Install Anaconda packages
- bash: |
    source activate coderec
    conda install --yes --quiet --name coderec scipy
  displayName: 'Replicate conda environement'
