# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: conda env create -f environment.yml
  displayName: 'Replicate conda environement'
- script: |
    cd user_study_webapp/app_study
    python server.py -p static/logs_user_extended_8.json -v static/video_cropped_8.mp4
  displayName: 'Run annotation tool server'

